
#ifndef PRESCALERS_CFG_H_
#define PRESCALERS_CFG_H_

#define	APB1_PRESCALER_VALUE	1U /* 0xxx: SYSCLK not divided */
#define	APB2_PRESCALER_VALUE	1U /* 0xxx: SYSCLK not divided */
#define	AHB_PRESCALER_VALUE	    1U  /* 0xxx: SYSCLK not divided */


#if (AHB_PRESCALER_VALUE == 1U)
    #define AHB_PRESCALER_REG RCC_CFGR_HPRE_DIV1
#elif (AHB_PRESCALER_VALUE == 2U)
    #define AHB_PRESCALER_REG RCC_CFGR_HPRE_DIV2
#elif (AHB_PRESCALER_VALUE == 4U)
    #define AHB_PRESCALER_REG RCC_CFGR_HPRE_DIV4
#elif (AHB_PRESCALER_VALUE == 8U)
    #define AHB_PRESCALER_REG RCC_CFGR_HPRE_DIV8
#elif (AHB_PRESCALER_VALUE == 16U)
    #define AHB_PRESCALER_REG RCC_CFGR_HPRE_DIV16
#elif (AHB_PRESCALER_VALUE == 64U)
    #define AHB_PRESCALER_REG RCC_CFGR_HPRE_DIV64
#elif (AHB_PRESCALER_VALUE == 128U)
    #define AHB_PRESCALER_REG RCC_CFGR_HPRE_DIV128
#elif (AHB_PRESCALER_VALUE == 256U)
    #define AHB_PRESCALER_REG RCC_CFGR_HPRE_DIV256
#elif (AHB_PRESCALER_VALUE == 512U)
    #define AHB_PRESCALER_REG RCC_CFGR_HPRE_DIV512
#endif /* AHB_PRESCALER_REG */

#if (APB1_PRESCALER_VALUE == 1U)
    #define APB1_PRESCALER_REG RCC_CFGR_PPRE1_DIV1
#elif (APB1_PRESCALER_VALUE == 2U)
    #define APB1_PRESCALER_REG RCC_CFGR_PPRE1_DIV2
#elif (APB1_PRESCALER_VALUE == 4U)
    #define APB1_PRESCALER_REG RCC_CFGR_PPRE1_DIV4
#elif (APB1_PRESCALER_VALUE == 8U)
    #define APB1_PRESCALER_REG RCC_CFGR_PPRE1_DIV8
#elif (APB1_PRESCALER_VALUE == 16U)
    #define APB1_PRESCALER_REG RCC_CFGR_PPRE1_DIV16
#endif /* APB1_PRESCALER */


#if (APB2_PRESCALER_VALUE == 1U)
    #define APB2_PRESCALER_REG RCC_CFGR_PPRE2_DIV1
#elif (APB2_PRESCALER_VALUE == 2U)
    #define APB2_PRESCALER_REG RCC_CFGR_PPRE2_DIV2
#elif (APB2_PRESCALER_VALUE == 4U)
    #define APB2_PRESCALER_REG RCC_CFGR_PPRE2_DIV4
#elif (APB2_PRESCALER_VALUE == 8U)
    #define APB2_PRESCALER_REG RCC_CFGR_PPRE2_DIV8
#elif (APB2_PRESCALER_VALUE == 16U)
    #define APB2_PRESCALER_REG RCC_CFGR_PPRE2_DIV16
#endif /* APB2_PRESCALER*/

#endif /* PRESCALERS_CFG_H_*/